# Generated by Django 5.2.4 on 2025-09-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_remove_rental_rental_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
